name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
      - 0.x.x

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Echo the greeting's time
        run: ls -la

  testJob:
    name: Test job
    runs-on: ubuntu-latest
    container: docker.pkg.github.com/upstain-me/docker/upstain-php:1.0.0

    steps:
      - uses: actions/checkout@v2
      - name: Echo the greeting's time
        run: ls -la
      - name: Test php
        run: php -v
